name: jusi_app_flutter
description: "Jusi App Flutter - LiveKit based video conferencing"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_background: ^1.1.0
  permission_handler: ^11.3.1
  provider: ^6.0.1
  logging: ^1.0.1
  shared_preferences: ^2.0.7
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.5
  dropdown_button2: ^2.3.6
  collection: '>=1.16.0'

  # 通过 pub 获取 client-sdk-flutter-2.6.3
  livekit_client: ^2.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/logo-dark.svg
